# Generated by Django 5.2.6 on 2025-10-10 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrackerApp', '0006_alter_auditlog_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
